login: &login
  adapter: mysql
  encoding: utf8
  collation: utf8_general_ci  
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost
     
development:
  database: va_development
  username: root
  password: 
  <<: *login
      
op_development:
  database: op_development
  username: root
  password: 
  <<: *login

op_production:
  database: op_production
  username: root
  password: 
  <<: *login
        
ref_area:
  database: ref_area_dev
  username: root
  password: 
  <<: *login
